#pragma once

#include <expected>

#include "core/util/file.h"
#include "renderer/text/font_atlas.h"

namespace ptgn::impl {

enum class FontCacheError {
	CannotOpen,
	InvalidMagic,
	UnsupportedVersion,
	ReadFailed,
	WriteFailed,
	InvalidPng,
	MissingFontData,
	MissingPngEnd,
	CrcMismatch
};

[[nodiscard]] std::expected<FontAtlasData, FontCacheError> LoadFontCache(FontBinary font_png);

[[nodiscard]] std::expected<FontAtlasData, FontCacheError> LoadFontCache(
	const path& cache_png_path
);

[[nodiscard]] std::expected<void, FontCacheError> WriteFontCache(
	const path& cache_png_path, const FontAtlasData& data
);

/// @return True if the PNG file at the given path is a valid font atlas generated by this engine.
/// This includes checking for the presence of the embedded FontData in the PNG metadata.
bool IsFontAtlasPng(const path& png_path);

} // namespace ptgn::impl