#pragma once

#include "core/config.h"

// #define PTGN_GL_DEBUG

#ifndef PTGN_DEBUG
#undef PTGN_GL_DEBUG
#endif

#ifdef PTGN_GL_DEBUG

#define PTGN_GL_DEBUG_BUFFERS
#define PTGN_GL_DEBUG_SHADERS
#define PTGN_GL_DEBUG_FRAMEBUFFERS
#define PTGN_GL_DEBUG_RENDERBUFFERS
#define PTGN_GL_DEBUG_TEXTURES
#define PTGN_GL_DEBUG_VERTEX_ARRAYS
#define PTGN_GL_DEBUG_RENDERER
#define PTGN_GL_DEBUG_CONTEXT

#endif