#pragma once

#include "ecs/ecs.h"

#include "protegon/circle.h"
#include "protegon/collision.h"
#include "protegon/color.h"
#include "protegon/engine.h"
#include "protegon/font.h"
#include "protegon/input.h"
#include "protegon/log.h"
#include "protegon/music.h"
#include "protegon/rectangle.h"
#include "protegon/rng.h"
#include "protegon/scene.h"
#include "protegon/sound.h"
#include "protegon/text.h"
#include "protegon/texture.h"
#include "protegon/type_traits.h"
#include "protegon/vector2.h"