#pragma once

#include <nlohmann/json.hpp>

using json = nlohmann::json;

#include "ecs/ecs.h"

//#include "protegon/button.h"
#include "protegon/circle.h"
#include "protegon/collision.h"
#include "protegon/color.h"
#include "protegon/debug.h"
#include "protegon/engine.h"
#include "protegon/event.h"
#include "protegon/events.h"
#include "protegon/font.h"
#include "protegon/file.h"
#include "protegon/grid.h"
#include "protegon/hash.h"
#include "protegon/input.h"
#include "protegon/key.h"
#include "protegon/line.h"
#include "protegon/log.h"
#include "protegon/manager.h"
#include "protegon/math.h"
#include "protegon/mouse.h"
#include "protegon/path_planning.h"
#include "protegon/rectangle.h"
#include "protegon/resources.h"
#include "protegon/rng.h"
#include "protegon/scene.h"
#include "protegon/sound.h"
#include "protegon/surface.h"
#include "protegon/text.h"
#include "protegon/texture.h"
#include "protegon/time.h"
#include "protegon/timer.h"
#include "protegon/type_traits.h"
#include "protegon/vector2.h"
#include "protegon/window.h"
