# Search for protegon source and header files
file(GLOB_RECURSE PROTEGON_SOURCES CONFIGURE_DEPENDS LIST_DIRECTORIES false 
	"${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp")

file(GLOB_RECURSE PROTEGON_HEADERS CONFIGURE_DEPENDS LIST_DIRECTORIES false 
    "${CMAKE_CURRENT_SOURCE_DIR}/src/*.h" "${CMAKE_CURRENT_SOURCE_DIR}/include/*.h")

file(GLOB_RECURSE PROTEGON_TEST_SOURCES CONFIGURE_DEPENDS LIST_DIRECTORIES false 
    "${CMAKE_CURRENT_SOURCE_DIR}/tests/protegon/src/*.cpp")